# Generated by Django 4.1.1 on 2022-09-27 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_servico_icone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='imagem',
        ),
    ]
