# Generated by Django 4.1.1 on 2022-09-27 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_funcionario_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='imagem',
            field=models.ImageField(null=True, upload_to='equipe', verbose_name='Imagem'),
        ),
    ]
