# Generated by Django 4.1.1 on 2022-09-27 22:24

import core.models
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_funcionario_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='imagem',
            field=stdimage.models.StdImageField(force_min_size=False, null=True, upload_to=core.models.get_file_path, variations={}, verbose_name='Imagem'),
        ),
    ]
