# Generated by Django 4.1.1 on 2022-10-17 20:22

import core.models
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_funcionario_imagem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Produtos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criados",
                    models.DateField(auto_now_add=True, verbose_name="Criação"),
                ),
                (
                    "modificado",
                    models.DateField(auto_now=True, verbose_name="Atualização"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo?")),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "descricao",
                    models.TextField(max_length=200, verbose_name="Descrição"),
                ),
                ("preco", models.IntegerField(null=True, verbose_name="Preço")),
                (
                    "imagem",
                    stdimage.models.StdImageField(
                        force_min_size=False,
                        null=True,
                        upload_to=core.models.get_file_path,
                        variations={},
                        verbose_name="Imagem",
                    ),
                ),
                ("estoque", models.IntegerField(null=True, verbose_name="Estoque")),
            ],
            options={"verbose_name": "Produto", "verbose_name_plural": "Produtos",},
        ),
    ]
