# Generated by Django 4.1.1 on 2022-10-19 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_produtos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saldo',
            fields=[
                ('produtos_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.produtos')),
                ('saldo_inicial', models.IntegerField(null=True, verbose_name='Saldo inicial da empresa')),
            ],
            options={
                'verbose_name': 'Saldo',
            },
            bases=('core.produtos',),
        ),
    ]
