# Generated by Django 4.1.1 on 2022-10-06 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_produtos_estoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='estoque',
            field=models.IntegerField(max_length=10, null=True, verbose_name='Estoque'),
        ),
    ]
