# Generated by Django 4.1.1 on 2022-10-21 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_produtos_saldo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='saldo',
        ),
    ]
