# Generated by Django 4.1.1 on 2022-10-23 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_saldo_saldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='saldo',
            name='produto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.produtos'),
        ),
    ]
